CREATE TABLE IF NOT EXISTS EMPLOYEES {
    EMP_ID INT PRIMARY KEY NOT NULL,
    EMP_NAME VARCHAR(50),
    EMP_DEPARTMENT VARCHAR(50),
    EMP_CITY VARCHAR(20),
    EMP_DEPT_ID INT,
    CONSTRAINT FK_EMP_DEPT_ID FOREIGN KEY(EMP_DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
};

CREATE TABLE IF NOT EXISTS DEPARTMENT {
    DEPT_ID INT PRIMARY KEY NOT NULL,
    DEPT_NAME VARCHAR(30) NOT NULL,
};

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Rahul Sharma','Developer','Bhiwani',20),
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Shubham Mishra','Developer','Gorakhpur',20),
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Ankur Verma','Developer','Rohtak',20),
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Shreejita Roy','Developer','Kolkata',20),
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Suman Kumar Maharana','Sr Developer','Orissa',21),
INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, EMP_DEPARTMENT, EMP_CITY, EMP_DEPT_ID) VALUES (1,'Junaid','Sr Developer','Hyderabad',21);

INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (20,'Developer'),
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (21,'Sr Developer');



